### ISSUE TITLE
VS Code on Mac -- Theme continually shows "reload" even after reload

### ISSUE THREAD

**Issue by jamonholmgren** [IonicaBizau/msdos-editor-vs-theme#7]
Thanks for making this theme! I really appreciate it.

When I installed on VS Code / macOS, the extension simply shows "Reload" even after reloading it several times and closing VS Code / reopening.

![image](https://user-images.githubusercontent.com/1479215/35158979-a3215eea-fced-11e7-8a3d-5211656caa29.png)

I uninstalled it and reinstalled it but no progress.

Is there a way to see any errors it displays?

**Comment by ComFreek** [comment]
I am facing the same problem with VS Code

**Comment by IonicaBizau** [comment]
I'm on it.

**Comment by IonicaBizau** [comment]
I had exactly the same issue, but after restarting the computer I couldn't reproduce it anymore... 

What I noticed is that the font family is not preserved. I had to add in the Settings:

```js
"editor.fontFamily": "'Perfect DOS VGA 437 Win'"
```

**Comment by jamonholmgren** [comment]
Full reboot didn't fix the problem for me. :/

**Comment by jordanmc** [comment]
Removing "main": "index.js" from package.json seemed to fix it for me, unless it was a coincidence.

**Comment by IonicaBizau** [comment]
Interesting... Could maybe test adding it back and removing it?

**Comment by jordanmc** [comment]
I added it back, and disabled extension, and it wouldn't enable again (kept asking to reload).

Removing it again, it worked after pressing reload. It does seem to be related.

**Comment by IonicaBizau** [comment]
@ComFreek @jamonholmgren Maybe can you check if this works?

**Comment by ComFreek** [comment]
Yay, I can confirm that it only works without it!

I opened this cloned repo in VS code and pressed F5 (as per [this guide](https://code.visualstudio.com/docs/extensions/developing-extensions)). Then a new VS Code window pops up and displays the following error message:

> [C:\Users\ComFreek\.vscode\extensions\ionicabizau.ms-dos-editor-theme-1.0.2]: properties `activationEvents` and `main` must both be specified or must both be omitted

Removing `main` from `package.json` fixed it.

**Comment by IonicaBizau** [comment]
Indeed, the `main.js` wasn't even existing. I removed the field from `package.json`, republished and it seems it works.

Thanks, @jordanmc and @ComFreek! :rocket:
