### ISSUE TITLE
Some Installation Instructions Unclear

### ISSUE THREAD

**Issue by LilithTundrus** [IonicaBizau/msdos-editor-vs-theme#8]
Hi, I read your contributing procedures and opened an issue before making changes to the README.MD file.

Most people don't know how to install fonts on Windows/Mac systems even though it's relatively simple. It'd be a good idea to have a short blurb about installing fonts.

Another thing that would help users is providing a link to the VS-Code store for this theme as well as how to add the font to the VS Code font preferences since they can be a bit confusing.

Thanks!

**Comment by IonicaBizau** [comment]
Contributions are welcome in that direction! :)
